### PR TITLE
Update on MER PMTCT STAT Report to v2.2

### PR DESCRIPTION
**Pull request by dbaluku**
https://trello.com/c/dtj5sReJ

Changes Made

- removed the MOH105 section in the report
- removed the section for male partners that were tested for HIV
-Added age dis-aggregations for 40-44 and 45-49 years 
- Removed  sections  for subtotals dis-aggregations

### CODE REVIEW

**Comment by dbaluku** [comment]
@ssmusoke  please review

**Comment by solemabrothers** [comment]
Percentage Column is missing data under results.

**Comment by ssmusoke** [comment]
@solemabrothers Please provide the name of the report which % column is missing the data

**Comment by solemabrothers** [comment]
Cell G4 of the PMTCT START Report is missing the percentages

**Pull request merged**
