### PR TITLE
Refactored the ART Register

### PR DESCRIPTION
**Pull request by carapai**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@carapai Can you fix the Travis failure

**Comment by ssmusoke** [comment]
@slubwama Please can you help me review this PR by running the register on your machine

**Comment by slubwama** [comment]
@carapai the report runs with accurate patient as expected
Thou some things are missing 
1. Viral Load
2. CD4
3. Addresses need to be corrected
4. ANC Number is missing.

**Comment by ssmusoke** [comment]
@carapai Not sure what the following files do:

1. summarize.gsp, ugandaemrreports.gsp, denormalize.gsp and related controllers 

2. MyTest.java 

3. Classes in the predicates package

**Comment by slubwama** [comment]
@carapai please put links to de-normalise    and summarize obs  in on the reporting page for easy access to it.

**Comment by ssmusoke** [comment]
@carapai @slubwama What is the purpose of the denormalize and summarize functionality? Its not clear to me? What ticket is it? What reports does it affect?

**Comment by ssmusoke** [comment]
@carapai please can you resolve the conflicts

**Comment by ssmusoke** [comment]
@carapai 

1. Art Start Date - format the column to a date 

2. Column 10 - weight MUAC (no MUAC shown)

**Pull request merged**
