### PR TITLE
Add Addresses to all Facility Reports

### PR DESCRIPTION
**Pull request by solemabrothers**
https://trello.com/c/9CmHYGIz/827-add-address-to-all-facility-reports

### CODE REVIEW

**Comment by dbaluku** [comment]
@solemabrothers  the following need improvement

- Address column in all reports should have two subtitles that is for parish and village
- Address title in stability report should match the case like other columns
- Address column should have a kind of uniformity with other personal data of the patients(you can put it on after the telephone or age )
-Lost clients and Due For VL reports require outfit spacing for the Addresses, the data is shrinking
-Active in care report had an address, please remove the address column in the code it useless now

**Comment by dbaluku** [comment]
@solemabrothers the following needs more improvement
- Missed appointments & stability report   cell headers need to be of the same case 
-ART care patient export address should be separated into village and parish
-Rapid Tests,Due For 1st PCR and Death list,Due for Appointment  reports need borders on headers

**Comment by dbaluku** [comment]
@solemabrothers 
- Missed Appointment is broken
- Due For 2nd PCR and Due for appointment  borders should be limited to the data columns only and  not the empty columns.
- Change Birth Date formats in the following reports ARTCare  patients,Transfer out , Lost clients and Lost to followup to the format MMM/dd/yyyy e.g Dec 06, 2004
-Column for patient name in ART care patient export report should be changed to Name from Names 

- Other date columns to format to the above format are 
- 1st PCR Due date, 2nd PCR Due Date, and Rapid test due date the three Infant EID reports 
- Next appointment date in due for appointment report

**Comment by solemabrothers** [comment]
@dbaluku please find here all the suggested changes to the PR.

**Comment by solemabrothers** [comment]
All the changes suggested are done

**Pull request merged**
