### PR TITLE
Correct label for CQI Indicator Report Row 16  from "addIndicator(dsd, "b1", "Children and Adolescents in care", activeChildrenAndAdolescents);" to "# unsuppressed and eligible for switch"

### PR DESCRIPTION
**Pull request by ssmusoke**
Screen Shot 2022-05-04 at 11 13 55

### CODE REVIEW

**Comment by dbaluku** [comment]
@ssmusoke please squash your commits

**Comment by ssmusoke** [comment]
@dbaluku You can squash and merge on PR merge

**Comment by dbaluku** [comment]
@ssmusoke You changed a report version of a different report

**Comment by ssmusoke** [comment]
@dbaluku Fixed - thanks for the review

**Pull request merged**
