### PR TITLE
WIP:HMIS072-Maternity-Register

### PR DESCRIPTION
**Pull request by moshonk**
@ssmusoke, Please find this clean PR for the Maternity Register Report.

### CODE REVIEW

**Comment by ningosi** [comment]
@ssmusoke @carapai what is pending on this PR?

**Comment by ssmusoke** [comment]
@ningosi I am looking over the PR it just came in this morning

**Comment by carapai** [comment]
@moshonk 
When using excel, the Excel template is not being found, but the web preview runs.
https://pastebin.com/Mx5yP8Wb

**Comment by moshonk** [comment]
@carapai There goes the commit.

**Comment by ningosi** [comment]
@carapai this PR has been here for a long time. What is required of it? Kindly find time and review it cc @moshonk

**Pull request merged**
