### PR TITLE
smc register refined work

### PR DESCRIPTION
**Pull request by ningosi**
@carapai and @slubwama I have been able to run this register over the de-identified database shared in less than 45 seconds. Please retry again and advice

### CODE REVIEW

**Comment by ssmusoke** [comment]
@ningosi The register now runs:

1. Change all dates to DD/MM/YY as per the register instructions 

2. Section 7.2 should have 3 columns 

3. Name of Health Unit - use the Global Property aijar.healthCenterName

**Comment by ningosi** [comment]
1 and 3 will be looked into shortly, but for 2 am NOT sure since the document am using has only one section @ssmusoke please check what I have attached on slack, if there is any other document please let me know. That is what @slubwama shared with us and he mentioned that it is the right and most correct one to use

**Comment by ssmusoke** [comment]
@ningosi Ignore 2 - looks like I had an older version of the register

**Comment by ssmusoke** [comment]
@ningosi Check the travis failure NameOfHealthUnitDatasetDefinition not imported

**Comment by ningosi** [comment]
@ssmusoke travis errors fixed

**Comment by ssmusoke** [comment]
@ningosi No data is returned in the report - see attachment 

[Safe_Male_Circumcision_Register_2017-08-18_21_15_15.xlsx](https://github.com/METS-Programme/openmrs-module-ugandaemr-reports/files/1235274/Safe_Male_Circumcision_Register_2017-08-18_21_15_15.xlsx)

**Comment by ningosi** [comment]
When I introduced a definition for the health facility name, I forgot to append the other  columns to the definition name. I will correct that and share

**Comment by ningosi** [comment]
@ssmusoke fixed

**Comment by ssmusoke** [comment]
@ningosi Feedback

1. Column M has SMCDate of TT1 

2. Columns R and S - put the Y and date on separate lines (use Alt + Enter for space in cell) 

3. Serial numbers have to be formatted as strings in Excel as preceeding zeros are lost

**Comment by ssmusoke** [comment]
@ningosi 15 year olds have records in both 5 < 15, and 15 < 49 columns, this may be the issue with age disegregations that I have been noticing. Can you review this with @moshonk too for the 105 2.1 - 2.7 reports...

@carapai Can you join this discussion too https://talk.openmrs.org/t/agecohortdefinition-for-age-ranges/12942 and https://github.com/METS-Programme/openmrs-module-ugandaemr-reports/pull/60

**Comment by ningosi** [comment]
@ssmusoke age aggregation sorted on the register, check it out. I think also the case of age between among the indicator report is sorted. Test and let me know

**Pull request merged**
