### PR TITLE
WIP:HMIS096A tb register

### PR DESCRIPTION
**Pull request by moshonk**
Please find the TB Register for your review @ssmusoke @carapai cc @ningosi

### CODE REVIEW

**Comment by ningosi** [comment]
@moshonk please resolve conflicts in this register @carapai please prioritize this for review, we need to move

**Comment by carapai** [comment]
@moshonk please delete the Maternity register on the reporting/reports folder, it conflicts with the one in the reports folder, this applies to TB register branch.
When I pull it add another Maternity Register the reporting/reports folder

**Comment by carapai** [comment]
@moshonk, there seems to be no any changes when I pull.
Can you pull from upstream and see if you see any changes

**Comment by moshonk** [comment]
@carapai  Could be you are not seeing any changes because a merge with the upstream occurred when I resolved the conflicts. I have removed the file MaternityRegister.xls from the reporting/reports folder cc @ningosi

**Comment by ningosi** [comment]
@carapai What is holding this cc @ssmusoke

**Comment by carapai** [comment]
@moshonk,
The query for computing the register is too complex and will be very difficult to maintain.
I am suggesting that if you can just
- get all obs for tb encounters for the month ie select * from obs where encounter_id in (select encounter_id from encounter_type = 'TB encounter')
- convert the query into a patientData, ie create dataDefinition and Evaluator
-  Then you can group the patientData by person_id you can use google guava.
-  Then you can loop through the grouped patientData
-  You can create helper function to get data.

**Comment by ningosi** [comment]
Carapai,

Is the code doing what is required?

Thanks

**Comment by ningosi** [comment]
@ssmusoke and @carapai what is stopping this PR from @moshonk into the main code base? it has taken too long here

**Comment by carapai** [comment]
@moshonk , please help me delete the SetupMarternityRegister.java on reporting/reports folder.
It is causing conflicts when you try to upload

**Comment by carapai** [comment]
@moshonk,
You need to check that the variable r[index] is not null before you call tostring. I am getting java.lang.NullPointerException for example on line 360. Continuation phase starts from 3 and not 2 also Continuation phase 4 is missing based on the excel template

**Comment by moshonk** [comment]
@carapai, Noted for action.

**Comment by moshonk** [comment]
@carapai, I have made adjustments to the report. Please check it out.
cc @ningosi @ssmusoke

**Comment by ssmusoke** [comment]
@carapai Please review this PR to finalize completion

**Comment by ningosi** [comment]
@ssmusoke can't we finish up with this register? You asked @carapai to finish it up but seems nothing is happening!

**Comment by ningosi** [comment]
@carapai  and @ssmusoke  what is holding this register to be merged? Is there anything I need to do? cc @moshonk

**Comment by ningosi** [comment]
I have NOT gotten clear picture of what is holding this register to be acted upon @ssmusoke @carapai @slubwama @jmpango This has taken long than expected. Is there anything pending that needs done? I can expedite that cc @moshonk

**Comment by ningosi** [comment]
We need this out of the way @carapai we are running short of time

**Pull request closed without merging**
