### PR TITLE
ANC Register

### PR DESCRIPTION
**Pull request by ningosi**
Contains files that populate the ANC Register. @ssmusoke look at it

### CODE REVIEW

**Comment by carapai** [comment]
There an error in Travis CI
Also when I try to upload the module, the error in this link appears
https://pastebin.com/WUpxCLYv

**Comment by carapai** [comment]
Do you use openjdk or oracle jdk?

**Comment by ningosi** [comment]
@ssmusoke @carapai This PR is ready for review. Also check if the Excel template is loading, I found it difficult to use it or advice the best way to use it

**Comment by carapai** [comment]
@ningosi, the excel file which downloads says it is corrupt and when opened, it has no headers rows. Please crosscheck the excel

**Comment by carapai** [comment]
@ningosi, the reporting module is not starting.
The excel template can not be read.
Check this pastebin
https://pastebin.com/NHrLTzDN

**Comment by ssmusoke** [comment]
@ningosi The report runs as expected. However the data needs to be separated into rows just like the actual register so that it is well aligned. Examples in the attachment (had to convert to xslx for GitHub upload only) 
[Feedback-Intergrated_Antenatal_Register_2017-05-24_17_03_50.xlsx](https://github.com/METS-Programme/openmrs-module-ugandaemr-reports/files/1025811/Feedback-Intergrated_Antenatal_Register_2017-05-24_17_03_50.xlsx)

**Comment by ningosi** [comment]
@ssmusoke that is helpful, I will look into those

**Pull request merged**
