### PR TITLE
Added 105Report Section 4

### PR DESCRIPTION
**Pull request by moshonk**
@ssmusoke, please find 105Report Section 4 extracted from the #53 PR
cc @ningosi

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama @carapai Can you find a facility with sample data for HTC so that we can test out this report section

**Comment by ningosi** [comment]
@moshonk conflicts to ressovle

**Comment by ningosi** [comment]
@slubwama @carapai have you found those as requested by @ssmusoke **Can you find a facility with sample data for HTC so that we can test out this report section** we need this out of the way

**Comment by ssmusoke** [comment]
@moshonk There are conflicts here that need to be resolved after the last PR merge

**Pull request merged**
