### PR TITLE
105 Section 5

### PR DESCRIPTION
**Pull request by ningosi**
Refine indicators and mappings for 105 section 5

### CODE REVIEW

**Comment by ssmusoke** [comment]
@ningosi Please resolve the conflicts here

**Comment by ssmusoke** [comment]
@ningosi For indicator S2 the total of the area from C9 to F13 should be the total number of SMC encounters. Currently there is missing data. Use the sample dataset for April 2017

**Comment by ningosi** [comment]
@ssmusoke test and review the comments I left on slack, and then advice me further!

**Comment by ssmusoke** [comment]
@ningosi The totals for S2 are more than the total number of circumcision encounters

**Comment by ningosi** [comment]
@ssmusoke I saw that and thought my queries were wrong and ended up applying dimensions of site type and method used to the total encounters only to discover that I was still getting the same numbers. I discovered later that 7 patients have more that one encounter for SMC and tends to have collected different obs that fall in both categories. I think my calculation is fine, the data need to be cleaned to get exact match.  Try this on your mysql **select COUNT(encounter_id), patient_id from encounter where encounter_type = 4 GROUP BY patient_id HAVING COUNT(encounter_id) > 1;**

**Comment by ssmusoke** [comment]
@ningosi The query returns 6 patients, however I have 14 additional encounters in the totals, rather than 6 or 7 based on the data. So there is still some duplication somewhere

**Comment by ningosi** [comment]
@ssmusoke I think those 6 entries you are getting are being repeated in both **facility/surgical/device** and **outreach/surgical/device** leading to additional 12 entries thus that difference in the encounters(which excluded duplicates because they are counted as sets as opposed to this dimension application which is dealt with as List before). If you look at the web view and check **S2-21 | Number of male circumcised (Total)** You will realize that all those are aggregated back to the total encounters without the duplicates

**Comment by ningosi** [comment]
@ssmusoke maybe we should try deleting the unwanted encounter plus associated obs and test again. The data is the cause of the errors!

**Comment by ssmusoke** [comment]
@ningosi will clean up the data and provide additional feedback

**Comment by ssmusoke** [comment]
@ningosi Just checked the data, the duplicate encounters are actually voided, so the queries and filters need to remove voided encounters and obs

**Comment by ningosi** [comment]
@ssmusoke Yes, but when I do this **select count(encounter_id) from encounter where encounter_type=4 and  encounter_datetime between '2017-04-01' AND '2017-04-30' and voided = 0;** I get more encounters than what is being returned by the definition

**Comment by ningosi** [comment]
@ssmusoke when I do this select **COUNT(encounter_id), patient_id from encounter where encounter_type = 4 and voided=0 GROUP BY patient_id HAVING COUNT(encounter_id) > 1;** I get 2 entries having duplicate encounters(totaling to 4 in number), still cleaning is required

**Comment by ningosi** [comment]
@ssmusoke from the patients that I get **11049** and **11070** and try and do this **select encounter_id, voided from encounter where patient_id in (11049,11070) and encounter_type=4 and encounter_datetime between '2017-04-01' and '2017-04-30';** I get 4 encounters recorded in the same period. Am going to void one for each and see the results

**Comment by ningosi** [comment]
@ssmusoke this 14 patients [10682,10749,10755,10760,10771,10772,10817,10826,10923,10993,11004,
11008,11009,11011] have both facility and camp recorded in the obs database and are NOT voided. Maybe Camp should be treated as facility as opposed to outreach as you suggested earlier. Test with this 
**select concept_id,value_coded,voided from obs where person_id=10755 and concept_id=162893;**

**Comment by ningosi** [comment]
Still waiting for your feedback on how to treat those patients who have both **facility** and **camp** in their site type. That is where the additional numbers are coming from @ssmusoke

**Pull request merged**
