### PR TITLE
Transfer In And Transfer Out Report Fixes

### PR DESCRIPTION
**Pull request by balukujr**
https://trello.com/c/N7oT7PLG

@ssmusoke  please review the PR

### CODE REVIEW

**Comment by ssmusoke** [comment]
@balukujr 

1. Transfer In Report 
- MOH Logo is stretched and not centered 
- Additional fields are not merged at the top and have a different font from the rest 
- Add HIV Enrolled Date (after Telephone Number) 
- Move Baseline Regimen, Baseline CD4 to after ART Start Date 

2. Transfer Out Report 
- MOH Logo is stretched and not centered 
- Additional fields are not merged at the top and have a different font from the rest 
- Move Art Start Date, Baseline CD4, Baseline Regimen to be after HIV Enrolled date 
- Add Most Recent Encounter, Current Regimen, Latest Viral Load Date, Viral Load Result

**Comment by balukujr** [comment]
@ssmusoke   I Worked on the  issues you noted , please review

**Comment by ssmusoke** [comment]
@balukujr 

1. Transfer Out List

    * MoH Logo is still not centered in the report 
    * Do not limit latest Viral Load and most recent encounters to the period covered by the report, since they could be before. 

2. Global: Viral Load data order is always Viral Load Date, Viral Load Qualitative, Viral Load copies/ml

**Comment by balukujr** [comment]
@ssmusoke

-  latest Viral Load and most recent encounters are not limited to the period rather by endDate and before
- Also what do you mean by Global

**Pull request merged**
