### PR TITLE
PMTCT reports 

### PR DESCRIPTION
**Pull request by ssmusoke**
Has error on effective date for the cohort definitions

### CODE REVIEW

**Comment by ssmusoke** [comment]
@carapai Please can you help me look into the error running the Infants due for 1st PCR report

**Comment by carapai** [comment]
OK

**Comment by carapai** [comment]
@ssmusoke  In the getExposedInfantsDueForFirstPCR Cohort Definition you put two parameters, startDate and EndDate, but when you calling the report, endDate is equal to startDate as specified in one of the parameters onOrBefore=${endDate},endDate=${endDate},effectiveDate=${endDate},startDate=${endDate}.
My Question is that what is significance of both startDate and endDate in the definition since we are working with ages?

**Comment by ssmusoke** [comment]
@carapai I kept adding those during testing. You can remove anything that is not needed

**Comment by ssmusoke** [comment]
@carapai Actually I added those two so that one can pick infants in between a start and end date later. 

The current getAllEid method only works between the start and end days of a month

**Comment by ssmusoke** [comment]
@carapai Actually I added those two so that one can pick infants in between a start and end date later. 

The current getAllEid method only works between the start and end days of a month

**Comment by ssmusoke** [comment]
@carapai Please review

**Comment by slubwama** [comment]
Exposed Infants Due for 1st PCR wrong label
Infants Due for 2nd DNA PCR report fails to run https://pastebin.com/Kgn9i70s
Infants Due for Rapid Test at 18 months of age https://pastebin.com/SnEvxzWB
Infants Due for Appointment works fine

**Pull request merged**
