### PR TITLE
WIP:Hmis072-maternity-register

### PR DESCRIPTION
**Pull request by moshonk**
@ssmusoke The maternity register is ready for review. cc @jmpango

### CODE REVIEW

**Comment by carapai** [comment]
Thank you for the pull request however I have some issues:
Can we change encounter type id to uuid.

**Comment by ssmusoke** [comment]
@moshonk 

1. The following XLS files should have no changes  
Facility ART Register, PreART Register, TransferOut List? 

2. Move all the reports to the ugandaemrreports.reporting package which is where we are refactoring classes.

**Comment by moshonk** [comment]
@ssmusoke, I have done the following:
* Removed the xls files from the commit
*Moved the report and related class files to the ugandaemrreports.reporting package
***However, I am unable to run the report after the refactoring (Fails with  **No reportDefinition with the given uuid** exception).

@carapai, I have changed reference to Encounter Type from ID to UUID

**Comment by ssmusoke** [comment]
@moshonk What I meant was that there are changes on the XLS files which should not happen at this time

**Pull request closed without merging**
