### PR TITLE
TB 009 Unit Register Report

### PR DESCRIPTION
**Pull request by dbaluku**
https://app.asana.com/0/0/1200134818051720/f

### CODE REVIEW

**Comment by slubwama** [comment]
@dbaluku where is the card for this PR

**Comment by slubwama** [comment]
@dbaluku I have created a patient and Enrolled them in the DS TB Program and eventually downloaded the  TB register. I have been able to discover the following so far

1. The Patient is tagged as transfer in yet they are not transfer in
2. Information about their treatment phases is not clearly indicated yet the patient in initial phase which is the same as intensive phase 
3. On the field of BMI I see a value BMI instead of the BMI Calculation
4. Options for column 9 (Pulmonary Bacteriologically Confirmed, PTB Pulmonary Clinically Diagnosed ,PTB Extra Pulmonary PTB) exit and one is picked for the patient why is this not filled
5. Why isn't the HIV status filled in column 18 yet a patient has one.

**Comment by dbaluku** [comment]
@slubwama issues 1, 3,4,5 have been worked on. 
- Issue 2  the treatment phases are as with the follow-up encounters but not from Enrollment encounters 
- Issues 5  the HIV data  filled ise from the TB Enrollment page not from the HIV ART Summary page as this is a DR TB Register in TB Clinic

**Comment by slubwama** [comment]
@dbaluku  resolve conflicts

**Pull request merged**
